export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; role: 'student' | 'admin'; created_at: string; updated_at: string }; Insert: { id: string; role?: 'student' | 'admin' }; Update: { role?: 'student' | 'admin' } };
      semesters: { Row: { id: string; name: string; display_order: number; active: boolean; created_at: string; updated_at: string }; Insert: { name: string; display_order?: number; active?: boolean }; Update: { name?: string; display_order?: number; active?: boolean } };
      subjects: { Row: { id: string; name: string; code: string; semester_id: string; description: string | null; department: string | null; credits: number | null; display_order: number; active: boolean; icon_name: string | null; color_tone: string | null; created_at: string; updated_at: string }; Insert: { name: string; code: string; semester_id: string; description?: string | null; department?: string | null; credits?: number | null; display_order?: number; active?: boolean; icon_name?: string | null; color_tone?: string | null }; Update: Partial<{ name: string; code: string; semester_id: string; description: string | null; department: string | null; credits: number | null; display_order: number; active: boolean; icon_name: string | null; color_tone: string | null }> };
      resource_categories: { Row: { id: string; name: string; description: string | null; display_order: number; active: boolean; icon_name: string | null; created_at: string; updated_at: string }; Insert: { name: string; description?: string | null; display_order?: number; active?: boolean; icon_name?: string | null }; Update: Partial<{ name: string; description: string | null; display_order: number; active: boolean; icon_name: string | null }> };
      folders: { Row: { id: string; subject_id: string; parent_folder_id: string | null; name: string; description: string | null; display_order: number; created_at: string; updated_at: string }; Insert: { subject_id: string; parent_folder_id?: string | null; name: string; description?: string | null; display_order?: number }; Update: Partial<{ subject_id: string; parent_folder_id: string | null; name: string; description: string | null; display_order: number }> };
      resources: { Row: { id: string; title: string; description: string | null; subject_id: string; folder_id: string; category_id: string; semester_id: string; file_path: string; file_name: string; file_size: number | null; mime_type: string; page_count: number | null; author_or_professor: string | null; academic_year: string | null; tags: string[]; status: 'draft' | 'published'; downloads_count: number; created_by: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['resources']['Row'], 'id' | 'created_at' | 'updated_at' | 'downloads_count'> & { id?: string; created_at?: string; updated_at?: string; downloads_count?: number }; Update: Partial<Database['public']['Tables']['resources']['Insert']> };
      feedback: { Row: { id: string; name: string; email: string | null; message: string; type: string; subject_requested: string | null; rating: number | null; status: 'unread' | 'read'; created_at: string }; Insert: { name: string; email?: string | null; message: string; type?: string; subject_requested?: string | null; rating?: number | null; status?: 'unread' | 'read' }; Update: Partial<Database['public']['Tables']['feedback']['Insert']> };
      bookmarks: { Row: { id: string; user_id: string; resource_id: string; created_at: string }; Insert: { user_id: string; resource_id: string }; Update: never };
      settings: { Row: { key: string; value: string; updated_at: string }; Insert: { key: string; value: string }; Update: { value?: string } };
      admin_activities: { Row: { id: string; actor_id: string | null; action: string; entity_type: string; entity_name: string; created_at: string }; Insert: { actor_id?: string | null; action: string; entity_type: string; entity_name: string }; Update: never };
    };
    Views: Record<string, never>;
    Functions: { is_admin: { Args: Record<string, never>; Returns: boolean } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
